use_frameworks!

platform :ios, '8.0'

target 'XYHelpKit_Example' do
  pod 'XYHelpKit', :path => '../'

  target 'XYHelpKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
